import './styles/globals.css'
import {Inter} from "next/font/google";

export const metadata = {
  title: 'Blife | Prueba Técnica',
  description: 'Generated by create next app',
  icons: {
    icon: '/blife.png',
  }
}
const inter = Inter({
  subsets: ['latin'],
  weight: ['500', '600', '700']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
